### ISSUE TITLE
deploy action failed

### ISSUE THREAD

**Issue by petravanhoudt** [mritogether/mritogether.github.io#38]
The deploy action of the latest pull request failed (time out error). Does anyone have a clue why this is happening? 
It worked locally for me.

**Comment by fsantini** [comment]
Maybe it's a server problem (overloaded or something). Try making a dummy commit and build it again. 

⁣Get BlueMail for Android ​

**Comment by petravanhoudt** [comment]
yes that must have been it, because I tried again and it worked now!
